import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import Head from "next/head";

export const metadata: Metadata = {
  title: "Microbial Symphony",
  // description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <link rel="stylesheet" href="https://use.typekit.net/zur3vau.css" />
      </Head>
      <body>{children}</body>
    </html>
  );
}
